<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="LogicBuilder.App.Bsl.Business" Version="1.0.3" />
		<PackageReference Include="LogicBuilder.App.Utils" Version="1.0.7" />
		<PackageReference Include="LogicBuilder.Forms.Parameters" Version="2.2.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.11" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
		<PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.0" />
		<PackageReference Include="xunit.v3" Version="4.0.0" />
		<PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Enrollment.Data\Enrollment.Data.csproj" />
    <ProjectReference Include="..\Enrollment.Domain\Enrollment.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>